name: Costa Rica Property Scraper

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape-properties:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install puppeteer cheerio axios fs-extra crypto-js
        
    - name: Run property scraper
      run: node scripts/scraper.js
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
        EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Property Scraper Bot"
        git add database/properties/
        git add database/scraping/last-run.json
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update: Properties scraped $(date)"
          git push
        fi
        
  purge-old-properties:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * 0'  # Sunday at midnight
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install fs-extra
      
    - name: Purge old properties
      run: node scripts/purge-old-properties.js
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com" 
        git config --local user.name "Property Purger Bot"
        git add database/properties/
        if ! git diff --staged --quiet; then
          git commit -m "Auto-purge: Removed old properties $(date)"
          git push
        fi
        
  send-email-campaigns:
    runs-on: ubuntu-latest
    needs: scrape-properties
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install axios crypto-js
      
    - name: Send email campaigns
      run: node scripts/email-campaigns.js
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
        EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
        AWS_LAMBDA_PDF_URL: ${{ secrets.AWS_LAMBDA_PDF_URL }}